

export enum NodeInternalType {
  BASIC_BLOCK,
  CLASS,
  METHOD,
  FIELD,
  FILE,
  INSTRUCTION,
  METADATA,
  PACKAGE,
  SWITCH_STMT,
  SYSCALL,
  TAG_CATEGORY,
  CATCH_STMT,
  SWITCH_CASE,
  FUNC,
  EXEC_SECTION,
  VAR,
  INSTR_CPU,
  FILE_SECTION,
  PLATFORM_PPT,
  INTERNAL_DB,
  USER_ACCOUNT,
  USER_SESSION,
  USER_SESSION_DATA,
  DATA_SCOPE,
  KEY_POINT,
  HOOK_BUILDER_RULE,
  BOOKMARK_TYPE,
  BOOKMARK,
  HOOK_JAVA,
  HOOK_NATIVE,
  HOOK_FRAGMENT,
  HOOK_STRATEGY,
  HOOK_GROUP,
  HOOK_SET,
  SCRIPT,
  ANAL_STATE,
  TAG,
  DATA_BLOCK,
  STRING,
  ANDROID_ACTIVITY,
  ANDROID_PROVIDER,
  ANDROID_RECEIVER,
  ANDROID_SERVICE,
  ANDROID_PERM,
  INSPECTOR,
  HOOK_SESSION,
  RUNTIME_EVENT,
  HOOK_SYSCALL,
  TEST_CREDS,
  LIB_FP,
  DASHBOARD,
  CALL,
  NONE,
  ASSURANCE_MODEL,
  CONTROL,
  CASE,
  BRAND,
  DEVICE_MODEL,
  DEVICE,
  PROJECT,
  TOOL,
  INSPECTOR_PLUGIN,
  SCAN_ORDER,
  LOG,
  ASSURANCE_REPORT,
  PROJECT_INPUT,
  PRIMITIVE_TYPE,
  OBJECT_TYPE,
  BOM,
  OPERATOR,
  REVERSENSE_PRODUCT,
  ANDROID_MANIFEST,
  UI_ROLE,
  UI_CMP_TYPE,
  UI_CMP,
  UI_EVT_TYPE,
  UI_EVT,
  RESOURCE,
  ORG_UNIT,
  APP_UNIT,
  USER_GROUP,
  CREDENTIAL,
  CONNECTION,
  ACL_ROLE
}

export const NodeInternalTypeName = {
  [NodeInternalType.BASIC_BLOCK]: "BASIC_BLOCK",
  [NodeInternalType.CLASS]: "CLASS",
  [NodeInternalType.METHOD]: "METHOD",
  [NodeInternalType.FIELD]: "FIELD",
  [NodeInternalType.FILE]: "FILE",
  [NodeInternalType.INSTRUCTION]: "INSTRUCTION",
  [NodeInternalType.METADATA]: "METADATA",
  [NodeInternalType.PACKAGE]: "PACKAGE",
  [NodeInternalType.SWITCH_STMT]: "SWITCH_STMT",
  [NodeInternalType.SYSCALL]: "SYSCALL",
  [NodeInternalType.TAG_CATEGORY]: "TAG_CATEGORY",
  [NodeInternalType.CATCH_STMT]: "CATCH_STMT",
  [NodeInternalType.SWITCH_CASE]: "SWITCH_CASE",
  [NodeInternalType.FUNC]: "FUNC",
  [NodeInternalType.EXEC_SECTION]: "EXEC_SECTION",
  [NodeInternalType.VAR]: "VAR",
  [NodeInternalType.INSTR_CPU]: "INSTR_CPU",
  [NodeInternalType.FILE_SECTION]: "FILE_SECTION",
  [NodeInternalType.PLATFORM_PPT]: "PLATFORM_PPT",
  [NodeInternalType.INTERNAL_DB]: "INTERNAL_DB",
  [NodeInternalType.USER_ACCOUNT]: "USER_ACCOUNT",
  [NodeInternalType.USER_SESSION]: "USER_SESSION",
  [NodeInternalType.USER_SESSION_DATA]: "USER_SESSION_DATA",
  [NodeInternalType.DATA_SCOPE]: "DATA_SCOPE",
  [NodeInternalType.KEY_POINT]: "KEY_POINT",
  [NodeInternalType.HOOK_BUILDER_RULE]: "HOOK_BUILDER_RULE",
  [NodeInternalType.BOOKMARK_TYPE]: "BOOKMARK_TYPE",
  [NodeInternalType.BOOKMARK]: "BOOKMARK",
  [NodeInternalType.HOOK_JAVA]: "HOOK_JAVA",
  [NodeInternalType.HOOK_NATIVE]: "HOOK_NATIVE",
  [NodeInternalType.HOOK_FRAGMENT]: "HOOK_FRAGMENT",
  [NodeInternalType.HOOK_STRATEGY]: "HOOK_STRATEGY",
  [NodeInternalType.HOOK_GROUP]: "HOOK_GROUP",
  [NodeInternalType.HOOK_SET]: "HOOK_SET",
  [NodeInternalType.SCRIPT]: "SCRIPT",
  [NodeInternalType.ANAL_STATE]: "ANAL_STATE",
  [NodeInternalType.TAG]: "TAG",
  [NodeInternalType.DATA_BLOCK]: "DATA_BLOCK",
  [NodeInternalType.STRING]: "STRING",
  [NodeInternalType.ANDROID_ACTIVITY]: "ANDROID_ACTIVITY",
  [NodeInternalType.ANDROID_RECEIVER]: "ANDROID_RECEIVER",
  [NodeInternalType.ANDROID_PROVIDER]: "ANDROID_PROVIDER",
  [NodeInternalType.ANDROID_SERVICE]: "ANDROID_SERVICE",
  [NodeInternalType.ANDROID_PERM]: "ANDROID_PERM",
  [NodeInternalType.INSPECTOR]: "INSPECTOR",
  [NodeInternalType.HOOK_SESSION]: "HOOK_SESSION",
  [NodeInternalType.RUNTIME_EVENT]: "RUNTIME_EVENT",
  [NodeInternalType.HOOK_SYSCALL]: "HOOK_SYSCALL",
  [NodeInternalType.LIB_FP]: "LIB_FP",
  [NodeInternalType.TEST_CREDS]: "TEST_CREDS",
  [NodeInternalType.DASHBOARD]: "DASHBOARD",
  [NodeInternalType.CALL]: "CALL",
  [NodeInternalType.NONE]: "NONE",
  [NodeInternalType.ASSURANCE_MODEL]: "ASSURANCE_MODEL",
  [NodeInternalType.CONTROL]: "CONTROL",
  [NodeInternalType.CASE]: "CASE",
  [NodeInternalType.BRAND]: "BRAND",
  [NodeInternalType.DEVICE_MODEL]: "DEVICE_MODEL",
  [NodeInternalType.DEVICE]: "DEVICE",
  [NodeInternalType.PROJECT]: "PROJECT",
  [NodeInternalType.TOOL]: "TOOL",
  [NodeInternalType.INSPECTOR_PLUGIN]: "INSPECTOR_PLUGIN",
  [NodeInternalType.SCAN_ORDER]: "SCAN_ORDER",
  [NodeInternalType.LOG]: "LOG",
  [NodeInternalType.ASSURANCE_REPORT]: "ASSURANCE_REPORT",
  [NodeInternalType.PROJECT_INPUT]: "PROJECT_INPUT",
  [NodeInternalType.BOM]: "BOM",
  [NodeInternalType.OPERATOR]: "OPERATOR",
  [NodeInternalType.REVERSENSE_PRODUCT]: "REVERSENSE_PRODUCT",
  [NodeInternalType.ANDROID_MANIFEST]: "ANDROID_MANIFEST",
  [NodeInternalType.UI_ROLE]: "UI_ROLE",
  [NodeInternalType.UI_CMP_TYPE]: "UI_CMP_TYPE",
  [NodeInternalType.UI_CMP]: "UI_CMP",
  [NodeInternalType.UI_EVT_TYPE]: "UI_EVT_TYPE",
  [NodeInternalType.UI_EVT]: "UI_EVT",
  [NodeInternalType.RESOURCE]: "RESOURCE",
  [NodeInternalType.ORG_UNIT]: "ORG_UNIT",
  [NodeInternalType.APP_UNIT]: "APP_UNIT",
  [NodeInternalType.USER_GROUP]: "USER_GROUP",
  [NodeInternalType.CREDENTIAL]: "CREDENTIAL",
  [NodeInternalType.CONNECTION]: "CONNECTION",
  [NodeInternalType.ACL_ROLE]: "ACL_ROLE"
}




/**
 * Helper to handle "not typed" object representing node
 * @class
 */
export class NodeTypeHelper {

  static UID_MAPPING = {
    [NodeInternalType.BASIC_BLOCK]: "name",
    [NodeInternalType.CLASS]: "name",
    [NodeInternalType.METHOD]: "__signature__",
    [NodeInternalType.FIELD]: "__signature__",
    [NodeInternalType.FILE]: "_uid",
    [NodeInternalType.INSTRUCTION]: "_raw",
    [NodeInternalType.METADATA]: "alias",
    [NodeInternalType.PACKAGE]: "name",
    [NodeInternalType.KEY_POINT]: "name",
    [NodeInternalType.RUNTIME_EVENT]: "id"
  }

  /**
   * To get UID of a node when object instance is not representative
   *
   * @param pNode
   * @param pNodeType
   */
  static getUIDof( pNode:any, pNodeType:number = -1):string{
    const type = (pNodeType == -1 ? pNode.__ : pNodeType);

    const pptUID = (NodeTypeHelper.UID_MAPPING as any)[type];
    console.log(pNode, type, pptUID);
    if(pptUID != null){
      return pNode[pptUID];
    }else{
      return pNode._uid;
    }
  }
}
